### ISSUE TITLE
Dynamic Vesting Period progress bar over than 100%

### ISSUE THREAD

**Issue by clintnetwork** [parasol-finance/application#174]
Details
---

<img width="435" alt="Screenshot 2022-05-29 at 19 40 12" src="https://user-images.githubusercontent.com/5221349/170884032-4db5a296-bb74-4896-b3bb-39307e6e1652.png">

**Comment by haodev007** [comment]
This issue resolved in #173 PR.
Please review it and close this issue as completed

**Comment by clintnetwork** [comment]
Please @haodev007 always assign issue in PR, it will automatically closes the issue
